<?php

namespace App\Console\Commands;

use App\Models\User;
use App\Models\UserMcpKey;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class CreateUserMcpKeysCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'ideatub:create-mcp-keys
                            {--force : Create a new key even if the user already has one}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create one MCP key per user (ideatub_ + random). Output plain keys once for users to copy.';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $force = $this->option('force');
        $users = User::query()->orderBy('id')->get();

        if ($users->isEmpty()) {
            $this->warn('No users found. Create users first.');

            return self::FAILURE;
        }

        $created = 0;
        $skipped = 0;

        foreach ($users as $user) {
            $existing = $user->userMcpKeys()->first();

            if ($existing && ! $force) {
                $this->line("User #{$user->id} ({$user->email}): already has an MCP key, skipping (use --force to create another).");
                $skipped++;

                continue;
            }

            $plainKey = 'ideatub_'.Str::random(32);
            $keyHash = UserMcpKey::hashKey($plainKey);

            UserMcpKey::query()->create([
                'user_id' => $user->id,
                'key_hash' => $keyHash,
                'label' => 'Generated by ideatub:create-mcp-keys',
            ]);

            $this->line("User #{$user->id} ({$user->email}):");
            $this->info("  MCP key (copy once, then store securely): {$plainKey}");
            $this->newLine();
            $created++;
        }

        $this->info("Done. Created {$created} key(s), skipped {$skipped} user(s).");

        return self::SUCCESS;
    }
}
